languageCode = "zh-CN"
defaultContentLanguage =      "zh-CN"
title = "GOPROXY IN ACTION"
publishdir = "../docs"
theme = "beg"
disqusShortname = "goproxy"
ignoreFiles = [ "\\.none$"]
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10
paginatePath = "page"
enableRobotsTXT = true
[menu]
  [[menu.main]]
    identifier = "download"
    name = "下载"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://github.com/snail007/goproxy/releases/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "关于"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 2

  # [[menu.main]]
  #   identifier = "tags"
  #   name = "TAGS"
  #   post = "<span class='alert'>New!</span>"
  #   pre = "<i class='fa fa-road'></i>"
  #   url = "/tags/"
  #   weight = -100